/**
 * Style Dictionary config.
 * Source of truth: tokens.json (W3C DTCG — $value / $type, з aliasʼами {group.token}).
 * Виходи:
 *   - src/styles/tokens.css          → :root { --... } CSS-змінні (з ланцюжком aliasʼів)
 *   - src/styles/tailwind.tokens.cjs → Tailwind preset, що вказує на ті самі CSS-змінні
 *
 * Bridge: клас на кшталт `bg-brand-primary` резолвиться у `var(--brand-primary)`,
 * тож змінивши токен у tokens.json (і перебілдивши) ти змінюєш і CSS, і Tailwind одразу.
 */

/** Кастомний формат: Tailwind preset, прив'язаний до згенерованих CSS-змінних. */
function tailwindPreset({ dictionary }) {
  const colors = {};
  const spacing = {};
  const borderRadius = {};
  const fontFamily = {};
  const fontWeight = {};
  const fontSize = {};

  for (const token of dictionary.allTokens) {
    const cssVar = `var(--${token.name})`;
    const type = token.$type ?? token.type;
    const path = token.path;
    // ключ = вже-kebab-ім'я CSS-змінної без провідного "color-", щоб клас збігався з var:
    // brand.primary → brand-primary, tableRow.bg → table-row-bg
    const key = token.name.replace(/^color-/, '');

    if (type === 'color') {
      colors[key] = cssVar;
    } else if (type === 'dimension') {
      if (path.includes('radius')) {
        borderRadius[key] = cssVar;
      } else if (path[0] === 'font' && path[1] === 'size') {
        fontSize[token.name.replace(/^font-size-/, '')] = cssVar;
      } else {
        spacing[key] = cssVar;
      }
    } else if (type === 'fontFamily') {
      fontFamily[path[path.length - 1]] = cssVar;
    } else if (type === 'fontWeight') {
      fontWeight[path[path.length - 1]] = cssVar;
    }
  }

  const preset = {
    theme: { extend: { colors, spacing, borderRadius, fontFamily, fontWeight, fontSize } },
  };

  return (
    '/**\n' +
    ' * Do not edit directly — generated by Style Dictionary from tokens.json.\n' +
    " * Використання (Tailwind config): presets: [require('./src/styles/tailwind.tokens.cjs')]\n" +
    ' */\n' +
    `module.exports = ${JSON.stringify(preset, null, 2)};\n`
  );
}

export default {
  source: ['tokens.json'],
  hooks: {
    formats: {
      'tailwind/preset': tailwindPreset,
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    tailwind: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tailwind.tokens.cjs',
          format: 'tailwind/preset',
        },
      ],
    },
  },
};
