/**
 * Do not edit directly — generated by Style Dictionary from tokens.json.
 * Використання (Tailwind config): presets: [require('./src/styles/tailwind.tokens.cjs')]
 */
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "blue-300": "var(--color-blue-300)",
        "blue-500": "var(--color-blue-500)",
        "blue-700": "var(--color-blue-700)",
        "base-black": "var(--color-base-black)",
        "base-white": "var(--color-base-white)",
        "base-transparent": "var(--color-base-transparent)",
        "gray-100": "var(--color-gray-100)",
        "gray-200": "var(--color-gray-200)",
        "gray-300": "var(--color-gray-300)",
        "gray-700": "var(--color-gray-700)",
        "gray-800": "var(--color-gray-800)",
        "red-500": "var(--color-red-500)",
        "red-600": "var(--color-red-600)",
        "brand-primary": "var(--brand-primary)",
        "brand-primary-hover": "var(--brand-primary-hover)",
        "brand-primary-active": "var(--brand-primary-active)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-title": "var(--text-title)",
        "text-disabled": "var(--text-disabled)",
        "text-error": "var(--text-error)",
        "text-on-brand": "var(--text-on-brand)",
        "border-default": "var(--border-default)",
        "border-active": "var(--border-active)",
        "border-error": "var(--border-error)",
        "border-disabled": "var(--border-disabled)",
        "surface-card": "var(--surface-card)",
        "surface-selected": "var(--surface-selected)",
        "surface-disabled": "var(--surface-disabled)",
        "button-bg-default": "var(--button-bg-default)",
        "button-bg-hover": "var(--button-bg-hover)",
        "button-bg-active": "var(--button-bg-active)",
        "button-bg-disabled": "var(--button-bg-disabled)",
        "button-text": "var(--button-text)",
        "button-text-disabled": "var(--button-text-disabled)",
        "input-text": "var(--input-text)",
        "input-placeholder": "var(--input-placeholder)",
        "input-border-default": "var(--input-border-default)",
        "input-border-error": "var(--input-border-error)",
        "card-bg": "var(--card-bg)",
        "card-border": "var(--card-border)",
        "card-border-hover": "var(--card-border-hover)",
        "card-text-title": "var(--card-text-title)",
        "card-text-secondary": "var(--card-text-secondary)",
        "table-row-bg": "var(--table-row-bg)",
        "table-row-border": "var(--table-row-border)",
        "table-row-border-hover": "var(--table-row-border-hover)",
        "table-row-bg-selected": "var(--table-row-bg-selected)",
        "table-row-text-title": "var(--table-row-text-title)"
      },
      "spacing": {
        "button-padding-x": "var(--button-padding-x)",
        "button-padding-y": "var(--button-padding-y)",
        "button-spacing": "var(--button-spacing)",
        "button-icon-size": "var(--button-icon-size)",
        "input-padding-x": "var(--input-padding-x)",
        "input-padding-y": "var(--input-padding-y)",
        "card-padding-x": "var(--card-padding-x)",
        "card-padding-y": "var(--card-padding-y)",
        "card-spacing": "var(--card-spacing)",
        "card-width": "var(--card-width)",
        "table-row-padding-x": "var(--table-row-padding-x)",
        "table-row-padding-y": "var(--table-row-padding-y)",
        "table-row-spacing": "var(--table-row-spacing)",
        "cell-padding-x": "var(--cell-padding-x)",
        "cell-padding-y": "var(--cell-padding-y)",
        "cell-spacing": "var(--cell-spacing)",
        "scale-8": "var(--scale-8)",
        "scale-12": "var(--scale-12)",
        "scale-16": "var(--scale-16)",
        "scale-20": "var(--scale-20)",
        "size-border-2": "var(--size-border-2)"
      },
      "borderRadius": {
        "button-radius": "var(--button-radius)",
        "card-radius": "var(--card-radius)",
        "table-row-radius": "var(--table-row-radius)"
      },
      "fontFamily": {
        "primary": "var(--font-family-primary)",
        "display": "var(--font-family-display)"
      },
      "fontWeight": {
        "regular": "var(--font-weight-regular)",
        "medium": "var(--font-weight-medium)",
        "bold": "var(--font-weight-bold)"
      },
      "fontSize": {
        "caption": "var(--font-size-caption)",
        "body-small": "var(--font-size-body-small)",
        "body-base": "var(--font-size-body-base)",
        "heading-h3": "var(--font-size-heading-h3)"
      }
    }
  }
};
